modLoader="javafml"
loaderVersion="[39,)"
issueTrackerURL="https://github.com/Brass-Goggled-Coders/NetherBarrels/issues"
license="MIT"

[[mods]]
    modId="nether_barrels"
    version="${file.jarVersion}"
    displayName="Transport"
    authors="SkySom"
    description='''
    '''

[[dependencies.nether_barrels]]
    modId="forge"
    mandatory=true
    versionRange="[39.1.0,)"
    ordering="NONE"
    side="BOTH"